## Tensor Import

In [1]:
import torch

## Tensor Basics

In [2]:
x = torch.tensor(5)
print(x)

x = torch.tensor((1,2))
print(x)

x = torch.empty(2,3)
print(x)

tensor(5)
tensor([1, 2])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [3]:
# check size
print("x.size(): ", x.size())
print("x.shape: ", x.shape)

x.size():  torch.Size([2, 3])
x.shape:  torch.Size([2, 3])


In [4]:
# check data type
print(x.dtype)

torch.float32


In [5]:
# requires_grad argument
# This will tell pytorch that it will need to calculate the gradients for this tensor
# later in your optimization steps
# e.g. this is a variable in your model that you want to optimize
x = torch.tensor([5.5, 3], requires_grad=True)
print(x)

tensor([5.5000, 3.0000], requires_grad=True)


In [6]:
# Operations
x = torch.ones(2, 3)
y = torch.rand(2, 3)

# addition
z = x + y

# subtraction
z = x - y

# multiplication
z = x * y

# division
z = x / y

print(x)
print(y)
print(z)



tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.2389, 0.0659, 0.6979],
        [0.9965, 0.3339, 0.2684]])
tensor([[ 4.1851, 15.1845,  1.4329],
        [ 1.0035,  2.9951,  3.7262]])


In [7]:
# Slicing
x = torch.rand(3, 3)
print(x)

print("x[:, 0]", x[:, 0])
print("x[0, :]", x[0, :])
print("x[0, 0]", x[0, 0])

# Get the actual value if only 1 element in your tensor
print("x[0, 0].item()", x[0, 0].item())

tensor([[0.0337, 0.4513, 0.0406],
        [0.3285, 0.0930, 0.7064],
        [0.1770, 0.4278, 0.6894]])
x[:, 0] tensor([0.0337, 0.3285, 0.1770])
x[0, :] tensor([0.0337, 0.4513, 0.0406])
x[0, 0] tensor(0.0337)
x[0, 0].item() 0.03366643190383911


In [8]:
# Reshape with torch.view()
x = torch.rand(4, 4)
y = x.view(16)
z = x.view(-1, 8) # if -1 pytorch will automatically determine the necessary size

print(x)
print(y)
print(z)

tensor([[0.0295, 0.6422, 0.1090, 0.4465],
        [0.2570, 0.5224, 0.7386, 0.6451],
        [0.8772, 0.5325, 0.0722, 0.8540],
        [0.2224, 0.5747, 0.3720, 0.7205]])
tensor([0.0295, 0.6422, 0.1090, 0.4465, 0.2570, 0.5224, 0.7386, 0.6451, 0.8772,
        0.5325, 0.0722, 0.8540, 0.2224, 0.5747, 0.3720, 0.7205])
tensor([[0.0295, 0.6422, 0.1090, 0.4465, 0.2570, 0.5224, 0.7386, 0.6451],
        [0.8772, 0.5325, 0.0722, 0.8540, 0.2224, 0.5747, 0.3720, 0.7205]])
