## Tensor Import

In [15]:
import torch

## 1. Tensor Basics

In [16]:
x = torch.tensor(5)
print(x)

x = torch.tensor((1,2))
print(x)

x = torch.empty(2,3)
print(x)

tensor(5)
tensor([1, 2])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [17]:
# check size
print("x.size(): ", x.size())
print("x.shape: ", x.shape)

x.size():  torch.Size([2, 3])
x.shape:  torch.Size([2, 3])


In [18]:
# check data type
print(x.dtype)

torch.float32


In [19]:
# requires_grad argument
# This will tell pytorch that it will need to calculate the gradients for this tensor
# later in your optimization steps
# e.g. this is a variable in your model that you want to optimize
x = torch.tensor([5.5, 3], requires_grad=True)
print(x)

tensor([5.5000, 3.0000], requires_grad=True)


### Operations with Tensors

In [20]:
# Operations
x = torch.ones(2, 3)
y = torch.rand(2, 3)

# addition
z = x + y

# subtraction
z = x - y

# multiplication
z = x * y

# division
z = x / y

print(x)
print(y)
print(z)



tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.6148, 0.6072, 0.2317],
        [0.2530, 0.3209, 0.7107]])
tensor([[1.6265, 1.6468, 4.3153],
        [3.9524, 3.1164, 1.4070]])


In [21]:
# Slicing
x = torch.rand(3, 3)
print(x)

print("x[:, 0]", x[:, 0])
print("x[0, :]", x[0, :])
print("x[0, 0]", x[0, 0])

# Get the actual value if only 1 element in your tensor
print("x[0, 0].item()", x[0, 0].item())

tensor([[0.2027, 0.4967, 0.9797],
        [0.6863, 0.0182, 0.9716],
        [0.8638, 0.0555, 0.3902]])
x[:, 0] tensor([0.2027, 0.6863, 0.8638])
x[0, :] tensor([0.2027, 0.4967, 0.9797])
x[0, 0] tensor(0.2027)
x[0, 0].item() 0.20274841785430908


In [22]:
# Reshape with torch.view()
x = torch.rand(4, 4)
y = x.view(16)
z = x.view(-1, 8) # if -1 pytorch will automatically determine the necessary size

print(x)
print(y)
print(z)

tensor([[0.7970, 0.9847, 0.8462, 0.4618],
        [0.8342, 0.7803, 0.0045, 0.3656],
        [0.8094, 0.5220, 0.5565, 0.5720],
        [0.7762, 0.7957, 0.0893, 0.9152]])
tensor([0.7970, 0.9847, 0.8462, 0.4618, 0.8342, 0.7803, 0.0045, 0.3656, 0.8094,
        0.5220, 0.5565, 0.5720, 0.7762, 0.7957, 0.0893, 0.9152])
tensor([[0.7970, 0.9847, 0.8462, 0.4618, 0.8342, 0.7803, 0.0045, 0.3656],
        [0.8094, 0.5220, 0.5565, 0.5720, 0.7762, 0.7957, 0.0893, 0.9152]])


### NumPy

Converting a Torch Tensor to a NumPy array and vice versa

In [ ]:
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [25]:
# Careful: If the Tensor is on the CPU (not the GPU),
# both objects will share the same memory location, so changing one
# will also change the other
a.add_(1)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [27]:
# numpy to torch with .from_numpy(x), or torch.tensor() to copy it
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a) # they share the same memory location
c = torch.tensor(a)
print(a)
print(b)
print(c)

# again be careful when modifying
a += 1
print(a)
print(b)
print(c)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


### GPU Support

By default all tensors are created on the CPU. But we can also move them to the GPU (if it's available ), or create them directly on the GPU.

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

x = torch.rand(2, 2).to(device) # move tensors to GPU device if available

# it is a small optimizations
x = torch.rand(2, 2, device=device)  # or directy create them on GPU if available

tensor([[0.4267, 0.7320],
        [0.4876, 0.8199]])


## 2. Autograd

In [ ]:
print("Autograd")